stages:
  - Building
  - Testing

build:
  stage: Building
  script:
    - whoami
    - export COMMIT_TIME=$(date)
    - sed -i "s/COMMIT/$CI_COMMIT_SHA/g" Server/version.json
    - sed -i "s/DATE/$COMMIT_TIME/g" Server/version.json
    - sed -i "s/Debug/Test/g" Server/version.json
  artifacts:
    name: 'abris-server-base'
    paths:
      - Server
   
test:
  stage: Testing
  image: php:7.3-cli
  before_script:
    - apt-get update
    - apt-get -y install wget libpq-dev libmagickwand-dev libzip-dev php*-mysql
    - pecl install imagick
    - pecl install xdebug
    - docker-php-ext-install mysqli
    - docker-php-ext-install pgsql
    - docker-php-ext-install zip
    - docker-php-ext-enable imagick
    - docker-php-ext-enable xdebug
  script:
    - wget -O phpunit https://phar.phpunit.de/phpunit-8.phar
    - chmod +x phpunit
    - cp tests/config_free.json Server/configs/config_free.json
    - mkdir report
    - export XDEBUG_MODE=coverage
    - ./phpunit --bootstrap tests/bootstrap.php --testsuite Base --coverage-html report
  artifacts:
    name: 'abris-server-base-report'
    paths:
      - report